// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLhNjNmHkGTRk3k0J2DLt_nz_rih4GyvE',
    appId: '1:152974848917:web:7ab814c96f187e96653c9c',
    messagingSenderId: '152974848917',
    projectId: 'depense-42c49',
    authDomain: 'depense-42c49.firebaseapp.com',
    storageBucket: 'depense-42c49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUftUr2kLmKIwpttLNUcd6SHHlfhv9tY',
    appId: '1:152974848917:android:0a8c831a59e0fbee653c9c',
    messagingSenderId: '152974848917',
    projectId: 'depense-42c49',
    storageBucket: 'depense-42c49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL1j8jGsGCsFLE5yvt7PUD90mgCW67dzo',
    appId: '1:152974848917:ios:09cbaf27044dfb35653c9c',
    messagingSenderId: '152974848917',
    projectId: 'depense-42c49',
    storageBucket: 'depense-42c49.appspot.com',
    iosBundleId: 'com.example.depense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL1j8jGsGCsFLE5yvt7PUD90mgCW67dzo',
    appId: '1:152974848917:ios:09cbaf27044dfb35653c9c',
    messagingSenderId: '152974848917',
    projectId: 'depense-42c49',
    storageBucket: 'depense-42c49.appspot.com',
    iosBundleId: 'com.example.depense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLhNjNmHkGTRk3k0J2DLt_nz_rih4GyvE',
    appId: '1:152974848917:web:6442eef94ad9af2c653c9c',
    messagingSenderId: '152974848917',
    projectId: 'depense-42c49',
    authDomain: 'depense-42c49.firebaseapp.com',
    storageBucket: 'depense-42c49.appspot.com',
  );
}
